/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package books_proj;

import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author driskimaulana
 */
public class AuthorPanel extends javax.swing.JPanel {

    /**
     * Creates new form AuthorPanel
     */
    Author author2;
    dbConnection conn = new dbConnection();
    String nama;
    int jmlBk;
    String img;
    public AuthorPanel(boolean empty){
        
    }
    
    public AuthorPanel(Author author) {
        initComponents();
        
        updateAuthorPanel.setVisible(false);
        
        author2 = new Author(author.getNama(), author.getJumlah_buku(), author.getImg(), author.getId());
        
        label_name.setText(author.getNama());
        label_jmlBuku.setText(author.getJumlah_buku() + " buku diterbitkan");
        
        BufferedImage image = null;
        try {
            image = ImageIO.read(getClass().getResource("/books_proj/images/"+author.getImg()));
            Image dImage = image.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
            label_img.setIcon(new ImageIcon(dImage));
        } catch (Exception e) {
            System.err.println("error: " + e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_delete = new javax.swing.JButton();
        label_name = new javax.swing.JLabel();
        label_jmlBuku = new javax.swing.JLabel();
        label_img = new javax.swing.JLabel();
        updateAuthorPanel = new javax.swing.JPanel();
        label_nama = new javax.swing.JLabel();
        label_jmlbk = new javax.swing.JLabel();
        label_imgbk = new javax.swing.JLabel();
        btn_submitupdatebk = new javax.swing.JButton();
        field_nama = new javax.swing.JTextField();
        field_jmlBuku = new javax.swing.JTextField();
        field_img = new javax.swing.JTextField();
        btn_update = new javax.swing.JToggleButton();

        setBackground(java.awt.Color.gray);
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 76, 76)));

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        label_name.setBackground(java.awt.Color.white);
        label_name.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        label_name.setText("Nama");

        label_jmlBuku.setBackground(java.awt.Color.white);
        label_jmlBuku.setText("Jumlah Buku");

        updateAuthorPanel.setBackground(java.awt.Color.gray);

        label_nama.setText("Nama");

        label_jmlbk.setText("Jumlah Buku");

        label_imgbk.setText("Image");

        btn_submitupdatebk.setText("Submit");
        btn_submitupdatebk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitupdatebkActionPerformed(evt);
            }
        });

        field_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_namaActionPerformed(evt);
            }
        });

        field_jmlBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_jmlBukuActionPerformed(evt);
            }
        });

        field_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_imgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updateAuthorPanelLayout = new javax.swing.GroupLayout(updateAuthorPanel);
        updateAuthorPanel.setLayout(updateAuthorPanelLayout);
        updateAuthorPanelLayout.setHorizontalGroup(
            updateAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateAuthorPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_submitupdatebk))
            .addGroup(updateAuthorPanelLayout.createSequentialGroup()
                .addGroup(updateAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nama)
                    .addComponent(label_jmlbk)
                    .addComponent(label_imgbk))
                .addGap(24, 24, 24)
                .addGroup(updateAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(field_nama, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                    .addComponent(field_jmlBuku)
                    .addComponent(field_img)))
        );
        updateAuthorPanelLayout.setVerticalGroup(
            updateAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateAuthorPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(updateAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_jmlBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_jmlbk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_img, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_imgbk))
                .addGap(18, 18, 18)
                .addComponent(btn_submitupdatebk))
        );

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(label_img, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_jmlBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                            .addComponent(label_name, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_update)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete)
                        .addGap(24, 24, 24))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateAuthorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_jmlBuku)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_delete)
                            .addComponent(btn_update))))
                .addGap(18, 18, 18)
                .addComponent(updateAuthorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        
        int yesOrNo = JOptionPane.showConfirmDialog(null, "Delete this field?", "Delete", JOptionPane.YES_NO_OPTION);
        
        if(yesOrNo == 0){
            conn.Connect();
            String sql = "DELETE FROM `author` WHERE `no_author`="+author2.getId();
            conn.Query(sql);

            setVisible(false);
        }
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void field_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_namaActionPerformed

    private void field_jmlBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_jmlBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_jmlBukuActionPerformed

    private void field_imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_imgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_imgActionPerformed

    private void btn_submitupdatebkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitupdatebkActionPerformed
        // TODO add your handling code here:
        conn.Connect();
        nama = field_nama.getText();
        jmlBk = Integer.valueOf(field_jmlBuku.getText());
        img = field_img.getText();
            
        System.out.println(jmlBk +" " + nama + " " + img + " " + author2.getId());
        String sql = "UPDATE `author` SET `jumlah_buku` = \'"+jmlBk+"\',`nama` = \'"+nama+"\',`img_author` = \'"+img+"\' WHERE `no_author` ="+author2.getId()+";";
        conn.Query(sql);
        
        label_name.setText(nama);
        label_jmlBuku.setText(jmlBk + " buku diterbitkan");
        
        BufferedImage image = null;
        try {
            image = ImageIO.read(getClass().getResource("/books_proj/images/"+img));
            Image dImage = image.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
            label_img.setIcon(new ImageIcon(dImage));
        } catch (Exception e) {
            System.err.println("error: " + e.getMessage());
        }
        
        updateAuthorPanel.setVisible(false);
        
    }//GEN-LAST:event_btn_submitupdatebkActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        if(btn_update.isSelected()){
            field_nama.setText(author2.getNama());
            field_jmlBuku.setText(Integer.toString(author2.getJumlah_buku()));
            field_img.setText(author2.getImg());
            updateAuthorPanel.setVisible(true);
        }else{
            updateAuthorPanel.setVisible(false);

        }
    }//GEN-LAST:event_btn_updateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_submitupdatebk;
    private javax.swing.JToggleButton btn_update;
    private javax.swing.JTextField field_img;
    private javax.swing.JTextField field_jmlBuku;
    private javax.swing.JTextField field_nama;
    private javax.swing.JLabel label_img;
    private javax.swing.JLabel label_imgbk;
    private javax.swing.JLabel label_jmlBuku;
    private javax.swing.JLabel label_jmlbk;
    private javax.swing.JLabel label_nama;
    private javax.swing.JLabel label_name;
    private javax.swing.JPanel updateAuthorPanel;
    // End of variables declaration//GEN-END:variables
}
