/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package books_proj;

import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author driskimaulana
 */
public class BooksPanel extends javax.swing.JPanel {

    /**
     * Creates new form BooksPanel
     */
    Buku tBook = new Buku();
    dbConnection conn = new dbConnection();
    public BooksPanel(boolean isEmpty){
        
    }
    
    public BooksPanel(Buku buku) {
        initComponents();
        
        updateBukuPanel.setVisible(false);
        
        label_judul.setText(buku.getJudul());
        label_penerbit.setText("Penerbit: " + buku.getPenerbit());
        label_pengarang.setText("Karya: " + buku.getAuthor());
        label_desc.setLineWrap(true);
        label_desc.setWrapStyleWord(true);
        label_desc.setText(buku.getDesc());
        
        tBook.setAuthor(buku.getAuthor());
        tBook.setDesc(buku.getDesc());
        tBook.setImg(buku.getImg());
        tBook.setJudul(buku.getJudul());
        tBook.setPenerbit(buku.getPenerbit());
        tBook.setNoBuku(buku.getNoBuku());
        
        
        BufferedImage image = null;
        try {
            image = ImageIO.read(getClass().getResource("/books_proj/images/"+buku.getImg()));
            Image dImage = image.getScaledInstance(100, 150, Image.SCALE_SMOOTH);
            label_img.setIcon(new ImageIcon(dImage));
        } catch (Exception e) {
            System.err.println("error: " + e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_delete = new javax.swing.JButton();
        label_judul = new javax.swing.JLabel();
        label_pengarang = new javax.swing.JLabel();
        label_img = new javax.swing.JLabel();
        label_penerbit = new javax.swing.JLabel();
        label_desc = new javax.swing.JTextArea();
        updateBukuPanel = new javax.swing.JPanel();
        Judul = new javax.swing.JLabel();
        label_author = new javax.swing.JLabel();
        label_updatePenerbit = new javax.swing.JLabel();
        label_updateImg = new javax.swing.JLabel();
        label_updateDesc = new javax.swing.JLabel();
        field_judul = new javax.swing.JTextField();
        field_author = new javax.swing.JTextField();
        field_penerbit = new javax.swing.JTextField();
        field_img = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        field_desc = new javax.swing.JTextArea();
        btn_update = new javax.swing.JToggleButton();

        jPanel1.setBackground(java.awt.Color.gray);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 76, 76)));

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        label_judul.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        label_judul.setText("Nama");

        label_pengarang.setText("Pengarang");

        label_penerbit.setText("Penerbit");

        label_desc.setBackground(java.awt.Color.gray);
        label_desc.setColumns(20);
        label_desc.setRows(5);

        updateBukuPanel.setBackground(java.awt.Color.gray);

        Judul.setText("Judul");

        label_author.setText("Pengarang");

        label_updatePenerbit.setText("Penerbit");

        label_updateImg.setText("Image");

        label_updateDesc.setText("Deskripsi");

        field_judul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_judulActionPerformed(evt);
            }
        });

        field_author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_authorActionPerformed(evt);
            }
        });

        field_penerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_penerbitActionPerformed(evt);
            }
        });

        field_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_imgActionPerformed(evt);
            }
        });

        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        field_desc.setColumns(20);
        field_desc.setRows(5);
        jScrollPane1.setViewportView(field_desc);

        javax.swing.GroupLayout updateBukuPanelLayout = new javax.swing.GroupLayout(updateBukuPanel);
        updateBukuPanel.setLayout(updateBukuPanelLayout);
        updateBukuPanelLayout.setHorizontalGroup(
            updateBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateBukuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateBukuPanelLayout.createSequentialGroup()
                        .addGroup(updateBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_author)
                            .addComponent(label_updatePenerbit)
                            .addComponent(label_updateImg)
                            .addComponent(label_updateDesc)
                            .addComponent(Judul))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(updateBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(field_judul)
                            .addComponent(field_author)
                            .addComponent(field_penerbit)
                            .addComponent(field_img)
                            .addComponent(jScrollPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateBukuPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_submit)))
                .addContainerGap())
        );
        updateBukuPanelLayout.setVerticalGroup(
            updateBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateBukuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Judul)
                    .addComponent(field_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_author, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_author))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_updatePenerbit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_img, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_updateImg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updateBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_updateDesc)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btn_submit))
        );

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_delete)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(label_img, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_penerbit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_pengarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_desc, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE))))
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(updateBukuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(label_img, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_delete)
                            .addComponent(btn_update)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_judul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_pengarang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_penerbit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addGap(28, 28, 28)
                .addComponent(updateBukuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        
        int yesOrNo = JOptionPane.showConfirmDialog(null, "Delete this field?", "Delete", JOptionPane.YES_NO_OPTION);
        
        if(yesOrNo == 0){
            conn.Connect();
            String sql = "DELETE FROM `buku` WHERE `nomor_buku`="+tBook.getNoBuku();
            conn.Query(sql);

            setVisible(false);
        }
        
       
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void field_judulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_judulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_judulActionPerformed

    private void field_authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_authorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_authorActionPerformed

    private void field_penerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_penerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_penerbitActionPerformed

    private void field_imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_imgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_imgActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        if(btn_update.isSelected()){
            field_author.setText(tBook.getAuthor());
            field_desc.setText(tBook.getDesc());
            field_img.setText(tBook.getImg());
            field_judul.setText(tBook.getJudul());
            field_penerbit.setText(tBook.getPenerbit());
            updateBukuPanel.setVisible(true);
        }else{
            updateBukuPanel.setVisible(false);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        conn.Connect();
        String author = field_author.getText();
        String desc = field_desc.getText();
        String img = field_img.getText();
        String judul = field_judul.getText();
        String penerbit = field_penerbit.getText();
        
        System.out.println(desc);
        
        String sql = "UPDATE `buku` SET `judul` = \'"+judul+"\',`penerbit` = \'"+penerbit+"\',`img_buku` = \'"+img+"\',`desc` = \'"+desc+"\',`author` = \'"+author+"\' WHERE `nomor_buku` ="+tBook.getNoBuku()+";";
        conn.Query(sql);
        
        updateBukuPanel.setVisible(false);
        
        label_judul.setText(judul);
        label_penerbit.setText("Penerbit: " + penerbit);
        label_pengarang.setText("Karya: " + author);
        label_desc.setLineWrap(true);
        label_desc.setWrapStyleWord(true);
        label_desc.setText(desc);
        
        
        BufferedImage image = null;
        try {
            image = ImageIO.read(getClass().getResource("/books_proj/images/"+img));
            Image dImage = image.getScaledInstance(100, 150, Image.SCALE_SMOOTH);
            label_img.setIcon(new ImageIcon(dImage));
        } catch (Exception e) {
            System.err.println("error: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btn_submitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Judul;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_submit;
    private javax.swing.JToggleButton btn_update;
    private javax.swing.JTextField field_author;
    private javax.swing.JTextArea field_desc;
    private javax.swing.JTextField field_img;
    private javax.swing.JTextField field_judul;
    private javax.swing.JTextField field_penerbit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_author;
    private javax.swing.JTextArea label_desc;
    private javax.swing.JLabel label_img;
    private javax.swing.JLabel label_judul;
    private javax.swing.JLabel label_penerbit;
    private javax.swing.JLabel label_pengarang;
    private javax.swing.JLabel label_updateDesc;
    private javax.swing.JLabel label_updateImg;
    private javax.swing.JLabel label_updatePenerbit;
    private javax.swing.JPanel updateBukuPanel;
    // End of variables declaration//GEN-END:variables
}
